MIssion4Practice/Models/gradeCalcClass.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4Practice.Models
{
    public class gradeCalcClass
    {
        [Required]
        [Range(0, 100, ErrorMessage = "Assignments score must be between 0 and 100")]
        public int Assignments { get; set; }
        
        [Required]
        [Range(0, 100, ErrorMessage = "Assignments score must be between 0 and 100")]
        public int GroupProject { get; set; }
       
        [Required]
        [Range(0, 100, ErrorMessage = "Assignments score must be between 0 and 100")]
        public int Quizzes { get; set; }
       
        [Required]
        [Range(0, 100, ErrorMessage = "Assignments score must be between 0 and 100")]
        public int Midterm { get; set; }
       
        [Required]
        [Range(0, 100, ErrorMessage = "Assignments score must be between 0 and 100")]
        public int Final { get; set; }
        
        [Required]
        [Range(0, 100, ErrorMessage = "Assignments score must be between 0 and 100")]
        public int Intex { get; set; }
    }
}

MIssion4Practice/Controllers/viewzController.cs
using Microsoft.AspNetCore.Mvc;
using Mission4Practice.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MIssion4Practice.Controllers
{
    public class viewzController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult gradeCalculator()
        {
            return View();
        }

        [HttpPost]
        public IActionResult gradeCalculator(gradeCalcClass model)
        {
            return View();
        }
    }
}

MIssion4Practice/Views/shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <title>@ViewData["Title"]</title>
    <!--favicon-->
    <link rel="icon" type="image/x-icon" href="img/favicon.png" />
    <!--link css and such-->
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
</head>
<body>
    <nav>
        <a asp-controller="viewz" asp-action="Index">Home</a>
        <a asp-controller="viewz" asp-action="gradeCalculator">Grade Calculator</a>
    </nav>
    <div>
        @RenderBody()
    </div>
    
    <script src="~/lib/jQuery/jquery-3.6.3.min.js"></script>
    <script src="~/js/gradeCalculator.js"></script>
</body>
</html>

MIssion4Practice/Views/viewz/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade Calculator";
}
<!-- Header that lists preferred name -->
<h1>Darby Mecham</h1>

<!-- Picture of something I enjoy-->
<h2>Something I enjoy</h2>
<h3>Being at the Beach</h3>
<p>I'm not sure what it is about the water, but I think the beach is the best place to be, and I ll take any opportunity I get to be on the beach with my friends/fam.</p>
<img src="img/IMG_2032.JPG" />

<!--A paragraph on what you hope to get out of this IS 413 class-->
<h2>What I Hope to Get Out of 413:</h2>
<p>In all honesty, I am incredibly intimidated/discouraged by programming. I have never felt like it was one of my strengths. By the end of this class I hope to have improved confidence in my ability to program, and know that I am capable of working through code-related problems.  <p>

    <!--A list of the Top #3 jobs you are most interested in pursuing when you graduate-->
    <h2>Top #3 Jobs I am Interested In</h2>
    <ul>
        <li>Project Managment</li>
        <li>Data Analytics</li>
        <li>Database Management</li>
    </ul>

MIssion4Practice/Views/viewz/gradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model gradeCalcClass;

<!-- inputs for grade calculator-->
<h2>Grade Calculator</h2>
<p> Please input your percentage for each of the following categories. (Don't use decimal form)</p>
<form method="post">
    <label>Assignments:</label>
    <input id="assign" asp-for="Assignments"/><br />
    <label>Group Project:</label>
    <input id="group" asp-for="GroupProject"/><br />
    <label>Quizzes:</label>
    <input id="quiz" asp-for="Quizzes"/><br />
    <label>Midterm Exam:</label>
    <input id="mid" asp-for="Midterm"/><br />
    <label>Final Exam:</label>
    <input id="final" asp-for="Final"/><br />
    <label>INTEX:</label>
    <input id="intex" asp-for="Intex"/><br /><br />
    <input id="btnsend" type="submit" value="Calculate Grade" />
</form>

<!-- outputting results-->
<p id="result"></p>